In [2]:
import numpy as np

## DataTypes & Attributes 

+ numpy main data types is **ndarray** (n-dimensional array)

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
#2d array
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#3d array
a3 = np.array([[[1,2,3.8],
                [4,5,6.7],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]
               ]])
a3

array([[[ 1. ,  2. ,  3.8],
        [ 4. ,  5. ,  6.7],
        [ 7. ,  8. ,  9. ]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

#### Attributes in numpy

+ **shape**

In [7]:
# for some nupmy not behave the way we want
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

+ **ndim** -> number of dimensions 

In [10]:
a1.ndim, a2.ndim, a3.ndim
#a1.ndim => tells the number of dimensions in an a1 array
#a2.ndim => tells the number of dimensions in an a2 array
#a3.ndim => tells the number of dimensions in an a3 array

(1, 2, 3)

+ **dtype**

In [11]:
a1.dtype, a2.dtype,a3.dtype

(dtype('int64'), dtype('int64'), dtype('float64'))

+ **size** -> it is tell the how element in an array

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

+ **type()**

In [13]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

> although the vary in size and shape at end there are `ndarray`

In [14]:
# Create dataframe using numpy array

In [17]:
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6