In [2]:
import numpy as np

## DataTypes & Attributes 

+ numpy main data types is **ndarray** (n-dimensional array)

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
#2d array
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#3d array
a3 = np.array([[[1,2,3.8],
                [4,5,6.7],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]
               ]])
a3

array([[[ 1. ,  2. ,  3.8],
        [ 4. ,  5. ,  6.7],
        [ 7. ,  8. ,  9. ]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

#### Attributes in numpy

+ **shape**

In [7]:
# for some nupmy not behave the way we want
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

+ **ndim** -> number of dimensions 

In [10]:
a1.ndim, a2.ndim, a3.ndim
#a1.ndim => tells the number of dimensions in an a1 array
#a2.ndim => tells the number of dimensions in an a2 array
#a3.ndim => tells the number of dimensions in an a3 array

(1, 2, 3)

+ **dtype**

In [11]:
a1.dtype, a2.dtype,a3.dtype

(dtype('int64'), dtype('int64'), dtype('float64'))

+ **size** -> it is tell the how element in an array

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

+ **type()**

In [13]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

> although the vary in size and shape at end there are `ndarray`

In [14]:
# Create dataframe using numpy array

In [17]:
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## Creating Numpy array

In [19]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

####  ones() 
fill with one for given shape 

In [21]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.shape, ones.dtype, ones.size

((2, 3), dtype('float64'), 6)

#### zeros()
fill with zero for given shape

In [24]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
zeros.shape, zeros.dtype, zeros.size

((2, 3), dtype('float64'), 6)

#### arange()

In [27]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

#### random.randint( low_value, high_value, size = () )

In [29]:
random_array = np.random.randint(0,15, size=(3,5))
random_array

array([[ 8,  7, 12, 12,  0],
       [ 6,  6,  8,  9,  6],
       [ 8,  6,  0, 13, 13]])

In [30]:
random_array.shape, random_array.dtype, random_array.size

((3, 5), dtype('int64'), 15)

#### random.random(shape)
It is very similar to javascript random function the numbers 
are going generate between `0.0` to `1.0`

In [32]:
random_array_2 = np.random.random((2,3))
random_array_2

array([[0.19790593, 0.46542928, 0.13542399],
       [0.52060406, 0.80064224, 0.2308488 ]])

In [33]:
random_array_2.shape, random_array_2.dtype, random_array_2.size

((2, 3), dtype('float64'), 6)

#### random.rand(shape)

In [38]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.07855121, 0.36189241, 0.49570747],
       [0.08334184, 0.54287318, 0.58801004],
       [0.98740433, 0.29812674, 0.22467681],
       [0.65775807, 0.68926121, 0.13323787],
       [0.74235853, 0.28537079, 0.11557549]])

In [39]:
random_array_3.shape, random_array_3.dtype, random_array_3.size

((5, 3), dtype('float64'), 15)

### Pseudo-random numbers

In [42]:
np.random.seed(7)
random_array_4 = np.random.randint(10,size=(5,2))
random_array

array([[ 8,  7, 12, 12,  0],
       [ 6,  6,  8,  9,  6],
       [ 8,  6,  0, 13, 13]])

In [46]:
np.random.seed(8)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.8734294 , 0.96854066, 0.86919454],
       [0.53085569, 0.23272833, 0.0113988 ],
       [0.43046882, 0.40235136, 0.52267467],
       [0.4783918 , 0.55535647, 0.54338602],
       [0.76089558, 0.71237457, 0.6196821 ]])

🌠👇

When put `random.seed()` in any cell like above two examples it make sure that it always produce same output

### Viewing array and matrices

In [47]:
np.unique(a1)

array([1, 2, 3])

In [48]:
a1[0]

1

In [49]:
a2[0]

array([1, 2, 3])

In [50]:
a3[0]

array([[1. , 2. , 3.8],
       [4. , 5. , 6.7],
       [7. , 8. , 9. ]])

In [56]:
a3, a3.shape

(array([[[ 1. ,  2. ,  3.8],
         [ 4. ,  5. ,  6.7],
         [ 7. ,  8. ,  9. ]],
 
        [[10. , 11. , 12. ],
         [13. , 14. , 15. ],
         [16. , 17. , 18. ]]]),
 (2, 3, 3))

In [68]:
a3[:,:2, :3]

array([[[ 1. ,  2. ,  3.8],
        [ 4. ,  5. ,  6.7]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ]]])

In [69]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[8, 9, 3, 4, 5],
         [5, 7, 9, 2, 6],
         [9, 5, 1, 6, 4],
         [5, 8, 0, 7, 2]],

        [[6, 7, 4, 8, 9],
         [6, 4, 5, 2, 2],
         [6, 6, 6, 7, 9],
         [6, 0, 9, 2, 7]],

        [[9, 2, 6, 3, 0],
         [9, 0, 0, 6, 9],
         [7, 4, 7, 9, 4],
         [8, 2, 7, 2, 8]]],


       [[[6, 5, 2, 3, 3],
         [8, 7, 9, 7, 3],
         [8, 0, 7, 3, 0],
         [9, 0, 1, 2, 6]],

        [[7, 3, 8, 2, 9],
         [6, 5, 1, 3, 0],
         [0, 8, 6, 7, 8],
         [1, 0, 8, 9, 5]],

        [[2, 2, 2, 7, 7],
         [7, 6, 0, 3, 2],
         [4, 1, 5, 6, 3],
         [3, 0, 4, 6, 8]]]])

In [70]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [75]:
#get the first 4 numbers of inner most arrays
a4[:,:,:,:4]

array([[[[8, 9, 3, 4],
         [5, 7, 9, 2],
         [9, 5, 1, 6],
         [5, 8, 0, 7]],

        [[6, 7, 4, 8],
         [6, 4, 5, 2],
         [6, 6, 6, 7],
         [6, 0, 9, 2]],

        [[9, 2, 6, 3],
         [9, 0, 0, 6],
         [7, 4, 7, 9],
         [8, 2, 7, 2]]],


       [[[6, 5, 2, 3],
         [8, 7, 9, 7],
         [8, 0, 7, 3],
         [9, 0, 1, 2]],

        [[7, 3, 8, 2],
         [6, 5, 1, 3],
         [0, 8, 6, 7],
         [1, 0, 8, 9]],

        [[2, 2, 2, 7],
         [7, 6, 0, 3],
         [4, 1, 5, 6],
         [3, 0, 4, 6]]]])

### Mainpulating and comparing numpy array

#### Arithmetic

In [77]:
a1

array([1, 2, 3])

In [79]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [80]:
# +
a1 + ones

array([2., 3., 4.])

In [81]:
# - 
a1 - ones

array([0., 1., 2.])

In [82]:
# *
a1 * ones

array([1., 2., 3.])

In [83]:
a1 

array([1, 2, 3])

In [84]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
# a1 * a2
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [87]:
# How can you reshape a2 to be compatible wiht a3 ?
# How to reshape numpy array 
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

>💡 numpy is so because it use something called **broadcast** 

In [88]:
a1 / ones

array([1., 2., 3.])

In [89]:
a2 / a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [90]:
# floor divison (round down)
a2 // a1

array([[1, 1, 1],
       [4, 2, 2]])

In [91]:
a3 ** 2

array([[[  1.  ,   4.  ,  14.44],
        [ 16.  ,  25.  ,  44.89],
        [ 49.  ,  64.  ,  81.  ]],

       [[100.  , 121.  , 144.  ],
        [169.  , 196.  , 225.  ],
        [256.  , 289.  , 324.  ]]])

In [104]:
# numpy arithmetic methods
np.square(a3), "add => ",  np.add(a1, ones)

(array([[[  1.  ,   4.  ,  14.44],
         [ 16.  ,  25.  ,  44.89],
         [ 49.  ,  64.  ,  81.  ]],
 
        [[100.  , 121.  , 144.  ],
         [169.  , 196.  , 225.  ],
         [256.  , 289.  , 324.  ]]]),
 'add => ',
 array([2., 3., 4.]))

In [94]:
a1 % 2

array([1, 0, 1])

In [105]:
# numpy arithmetic methods
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [106]:
# numpy arithmetic methods
np.log(a1)

array([0.        , 0.69314718, 1.09861229])